# NumPy Introduction

NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [1]:
import numpy as np

print("NumPy imported successfully!")

NumPy imported successfully!


## Creating Arrays from Lists

Python lists are flexible but not optimized for numerical computations. NumPy arrays provide better performance and additional functionality.

In [2]:
a_array = [1, 2, 3, 4, 5]
print(f"a_array: {a_array}")
print("Indexing: a_array[2] =", a_array[2])
print("Slicing: a_array[1:3] =", a_array[1:3])
print("Reverse: a_array[::-1] =", a_array[::-1])
print("Every other: a_array[::2] =", a_array[::2])

np_array = np.array([1, 2, 3, 4, 5])
print(f"\nnp_array: {np_array}")
print(f"type(np_array): {type(np_array)}")
print(f"Element type: type(np_array[2]) = {type(np_array[2])}")
print(f"Slicing: np_array[1:3] = {np_array[1:3]}")
print(f"Reverse: np_array[:-2] = {np_array[:-2]}")
np_array[2] = 100
print(f"After modification: np_array = {np_array}")

a_array: [1, 2, 3, 4, 5]
Indexing: a_array[2] = 3
Slicing: a_array[1:3] = [2, 3]
Reverse: a_array[::-1] = [5, 4, 3, 2, 1]
Every other: a_array[::2] = [1, 3, 5]

np_array: [1 2 3 4 5]
type(np_array): <class 'numpy.ndarray'>
Element type: type(np_array[2]) = <class 'numpy.int64'>
Slicing: np_array[1:3] = [2 3]
Reverse: np_array[:-2] = [1 2 3]
After modification: np_array = [  1   2 100   4   5]


## Multidimensional Arrays

NumPy supports multi-dimensional arrays, which are essential for matrices and higher-dimensional data structures.

In [3]:
np_mdarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D array:\n{np_mdarray}")
print(f"Shape: {np_mdarray.shape}")
print(f"Dimensions: {np_mdarray.ndim}")
print(f"Size: {np_mdarray.size}")
print(f"Data type: {np_mdarray.dtype}")

# Mixed types
np_mdarray_mixed = np.array([[1, 2, 3], [4, "Hello", 6], [7, 8, 9]])
print(f"\nMixed type array:\n{np_mdarray_mixed}")
print(f"Data type: {np_mdarray_mixed.dtype}")
print(f"Element [1][1]: {np_mdarray_mixed[1][1]} (type: {type(np_mdarray_mixed[1][1])})")

# Explicit dtype
np_mdarray_int = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int64)
print(f"\nExplicit int64 array:\n{np_mdarray_int}")
print(f"Data type: {np_mdarray_int.dtype}")

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int64

Mixed type array:
[['1' '2' '3']
 ['4' 'Hello' '6']
 ['7' '8' '9']]
Data type: <U21
Element [1][1]: Hello (type: <class 'numpy.str_'>)

Explicit int64 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type: int64


## Array Operations

NumPy allows element-wise operations on arrays, which are much faster than loops.

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a:", a)
print("b:", b)
print("a + b:", a + b)
print("a * b:", a * b)
print("a ** 2:", a ** 2)
print("np.sin(a):", np.sin(a))

# Matrix operations
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print("\nMatrix m1:\n", m1)
print("Matrix m2:\n", m2)
print("Matrix multiplication m1 @ m2:\n", m1 @ m2)

a: [1 2 3]
b: [4 5 6]
a + b: [5 7 9]
a * b: [ 4 10 18]
a ** 2: [1 4 9]
np.sin(a): [0.84147098 0.90929743 0.14112001]

Matrix m1:
 [[1 2]
 [3 4]]
Matrix m2:
 [[5 6]
 [7 8]]
Matrix multiplication m1 @ m2:
 [[19 22]
 [43 50]]


## Broadcasting

Broadcasting allows operations between arrays of different shapes by automatically expanding smaller arrays.

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

print("Array:\n", arr)
print("Scalar:", scalar)
print("Array + scalar:\n", arr + scalar)

# Broadcasting with different shapes
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print("\n2D array:\n", arr2d)
print("1D array:", arr1d)
print("2D + 1D (broadcasted):\n", arr2d + arr1d)

Array:
 [[1 2 3]
 [4 5 6]]
Scalar: 10
Array + scalar:
 [[11 12 13]
 [14 15 16]]

2D array:
 [[1 2 3]
 [4 5 6]]
1D array: [10 20 30]
2D + 1D (broadcasted):
 [[11 22 33]
 [14 25 36]]


## Random Arrays and Statistics

NumPy provides tools for generating random data and computing statistics.

In [6]:
np.random.seed(42)  # For reproducible results

random_arr = np.random.rand(3, 3)  # Uniform random between 0 and 1
print("Random array (uniform):\n", random_arr)

normal_arr = np.random.randn(5)  # Standard normal distribution
print("\nRandom array (normal):", normal_arr)

# Statistics
data = np.random.randint(1, 100, 10)
print("\nData:", data)
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Min:", np.min(data))
print("Max:", np.max(data))

Random array (uniform):
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Random array (normal): [-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901]

Data: [49 91 59 42 92 60 80 15 62 62]
Mean: 61.2
Median: 61.0
Standard deviation: 22.021807373601288
Min: 15
Max: 92


## Exercises

Try these exercises to practice NumPy:

1. Create a 3x3 identity matrix.
2. Generate a 1D array of 20 random integers between 1 and 100, then find the sum of all even numbers.
3. Create two 2x3 arrays and perform element-wise multiplication.
4. Reshape a 1D array of 12 elements into a 3x4 matrix.

In [ ]:
# Exercise solutions (uncomment to see)

# 1. Identity matrix
# identity = np.eye(3)
# print("Identity matrix:\n", identity)

# 2. Random array and sum of evens
# arr = np.random.randint(1, 101, 20)
# even_sum = np.sum(arr[arr % 2 == 0])
# print("Array:", arr)
# print("Sum of evens:", even_sum)

# 3. Element-wise multiplication
# a = np.array([[1, 2, 3], [4, 5, 6]])
# b = np.array([[2, 3, 4], [5, 6, 7]])
# result = a * b
# print("Element-wise multiplication:\n", result)

# 4. Reshape
# arr_1d = np.arange(12)
# reshaped = arr_1d.reshape(3, 4)
# print("Original:", arr_1d)
# print("Reshaped:\n", reshaped)

## Boolean Indexing

Use boolean arrays to filter elements that meet certain conditions.

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Array:", arr)

# Boolean mask
mask = arr > 5
print("Mask (arr > 5):", mask)
print("Elements > 5:", arr[mask])

# Multiple conditions
even_mask = arr % 2 == 0
print("Even elements:", arr[even_mask])

# Combining with assignment
arr[arr < 3] = 0
print("After setting < 3 to 0:", arr)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Mask (arr > 5): [False False False False False  True  True  True  True  True]
Elements > 5: [ 6  7  8  9 10]
Even elements: [ 2  4  6  8 10]
After setting < 3 to 0: [ 0  0  3  4  5  6  7  8  9 10]


## Fancy Indexing

Access multiple elements at once using arrays of indices.

In [8]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

indices = [1, 3, 5]
print("Array:", arr)
print("Indices:", indices)
print("Fancy indexed:", arr[indices])

# 2D fancy indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = [0, 2]
col_indices = [1, 2]
print("\nMatrix:\n", matrix)
print("Rows:", row_indices, "Cols:", col_indices)
print("Selected elements:", matrix[row_indices, col_indices])

# Modifying with fancy indexing
arr[indices] = 999
print("\nAfter modification:", arr)

Array: [ 10  20  30  40  50  60  70  80  90 100]
Indices: [1, 3, 5]
Fancy indexed: [20 40 60]

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rows: [0, 2] Cols: [1, 2]
Selected elements: [2 9]

After modification: [ 10 999  30 999  50 999  70  80  90 100]


## Sorting and Searching

NumPy provides efficient sorting and searching functions for arrays.

In [9]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Unsorted array:", unsorted)

sorted_arr = np.sort(unsorted)
print("Sorted array:", sorted_arr)

# Sort in-place
unsorted.sort()
print("Sorted in-place:", unsorted)

# Searching
arr = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])
print("\nArray:", arr)
print("Index of first 4:", np.where(arr == 4)[0])
print("Indices where > 3:", np.where(arr > 3)[0])

# Unique values
unique_vals = np.unique(arr)
print("Unique values:", unique_vals)

Unsorted array: [3 1 4 1 5 9 2 6]
Sorted array: [1 1 2 3 4 5 6 9]
Sorted in-place: [1 1 2 3 4 5 6 9]

Array: [1 2 3 4 5 4 3 2 1]
Index of first 4: [3 5]
Indices where > 3: [3 4 5]
Unique values: [1 2 3 4 5]


## Linear Algebra

NumPy's linalg module provides linear algebra operations like matrix inversion, eigenvalues, and determinants.

In [12]:
matrix = np.array([[4, 2], [1, 3]])
print("Matrix:\n", matrix)

# Determinant
det = np.linalg.det(matrix)
print("Determinant:", det)

# Inverse
inv_matrix = np.linalg.inv(matrix)
print("Inverse:\n", inv_matrix)

# Eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvals)
print("Eigenvectors:\n", eigenvecs)

# Matrix multiplication (dot product)
vec = np.array([1, 2])
result = matrix @ vec
print("Matrix @ vector:", result)

# Solve linear system Ax = b
b = np.array([6, 4])
x = np.linalg.solve(matrix, b)
print("Solution to Ax = b:", x)

Matrix:
 [[4 2]
 [1 3]]
Determinant: 10.000000000000002
Inverse:
 [[ 0.3 -0.2]
 [-0.1  0.4]]
Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
Matrix @ vector: [8 7]
Solution to Ax = b: [1. 1.]


## File I/O with NumPy

NumPy provides functions to save and load arrays to/from files efficiently.

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array to save:\n", arr)

# Save to .npy file
np.save('array.npy', arr)
print("Array saved to array.npy")

# Load from .npy file
loaded_arr = np.load('array.npy')
print("Loaded array:\n", loaded_arr)

# Save multiple arrays
arr2 = np.array([7, 8, 9])
np.savez('arrays.npz', first=arr, second=arr2)
print("Multiple arrays saved to arrays.npz")

# Load multiple arrays
loaded = np.load('arrays.npz')
print("First array:", loaded['first'])
print("Second array:", loaded['second'])

# Save to text file
np.savetxt('array.txt', arr, delimiter=',')
print("Array saved to array.txt")

# Load from text file
loaded_txt = np.loadtxt('array.txt', delimiter=',')
print("Loaded from text:\n", loaded_txt)

Array to save:
 [[1 2 3]
 [4 5 6]]
Array saved to array.npy
Loaded array:
 [[1 2 3]
 [4 5 6]]
Multiple arrays saved to arrays.npz
First array: [[1 2 3]
 [4 5 6]]
Second array: [7 8 9]
Array saved to array.txt
Loaded from text:
 [[1. 2. 3.]
 [4. 5. 6.]]


## Performance Comparison: NumPy vs Python Lists

NumPy arrays are optimized for numerical operations and are much faster than Python lists for large data.

In [14]:
import time

size = 1000000

# Python list
py_list = list(range(size))
start = time.time()
py_result = [x * 2 for x in py_list]
py_time = time.time() - start

# NumPy array
np_array = np.arange(size)
start = time.time()
np_result = np_array * 2
np_time = time.time() - start

print(f"Size: {size}")
print(f"Python list time: {py_time:.4f}s")
print(f"NumPy array time: {np_time:.4f}s")
print(f"NumPy is {py_time / np_time:.1f}x faster")

# Memory usage
import sys
print(f"\nMemory usage:")
print(f"Python list: {sys.getsizeof(py_list)} bytes")
print(f"NumPy array: {np_array.nbytes} bytes")

Size: 1000000
Python list time: 0.0516s
NumPy array time: 0.0043s
NumPy is 12.0x faster

Memory usage:
Python list: 8000056 bytes
NumPy array: 8000000 bytes
